version: 2.1

orbs: 
  sonarcloud: sonarsource/sonarcloud@1.0.3
  
workflows:
  test-deploy:
    jobs:
      - test
          

jobs:
 test:
   docker:
     - image: cimg/node:14.13.0
   steps:
     - checkout
     - run:
         name: Insall Dependencies
         command: npm install
     - run:
         name: Run Testt
