version: 2.1

orbs: 
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
 test:
   docker:
     - image: cimg/node:14.13.0
   steps:
     - checkout
     - run:
          name: Run Tests
          command: npm run test     
     - sonarcloud/scan
workflows:
  test-deploy:
  on:
   pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    jobs:
    - test:
          context: sonarcloud
