version: 2.1

orbs: 
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
 test:
   docker:
     - image: cimg/node:14.13.0
   steps:
     - checkout
     - sonarcloud/scan

workflows:
  test-deploy:
    jobs:
      - test:
          context: SonarCloud Analysis
          
